services:
  service1:
    build: ./service1
    environment:
      OTEL_SERVICE_NAME: "service1"
      OTEL_TRACES_EXPORTER: "otlp" # , zipkin"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
#      OTEL_EXPORTER_ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
      OTEL_LOGS_EXPORTER: "logging"
      OTEL_METRICS_EXPORTER: "prometheus"
      OTEL_EXPORTER_PROMETHEUS_HOST: "0.0.0.0"
      OTEL_EXPORTER_PROMETHEUS_PORT: "9464"
    ports:
      - "8081:8081"
    container_name: service1
    depends_on:
      - service2

  service2:
    build: ./service2
    environment:
      OTEL_SERVICE_NAME: "service2"
      OTEL_TRACES_EXPORTER: "otlp" #, zipkin"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
#      OTEL_EXPORTER_ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
      OTEL_LOGS_EXPORTER: "logging"
      OTEL_METRICS_EXPORTER: "prometheus"
      OTEL_EXPORTER_PROMETHEUS_HOST: "0.0.0.0"
      OTEL_EXPORTER_PROMETHEUS_PORT: "9464"
    ports:
      - "8082:8082"
    container_name: service2
    depends_on:
      - service3

  service3:
    build: ./service3
    environment:
      OTEL_SERVICE_NAME: "service3"
      OTEL_TRACES_EXPORTER: "otlp" #, zipkin"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
#      OTEL_EXPORTER_ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
      OTEL_LOGS_EXPORTER: "logging"
      OTEL_METRICS_EXPORTER: "prometheus"
      OTEL_EXPORTER_PROMETHEUS_HOST: "0.0.0.0"
      OTEL_EXPORTER_PROMETHEUS_PORT: "9464"
    container_name: service3
    depends_on:
      - jaeger
      # - zipkin
    ports:
      - "8083:8083"

  # loki:
  #   image: grafana/loki:latest
  #   ports:
  #     - "3100:3100"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: always
    depends_on:
      - service1
      - service2
      - service3
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - ./docker/grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one
    # image: jaegertracing/jaeger:2.1.0
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: always
    ports:
      - "16686:16686"
      - "14250:14250"
      - "5778:5778" 
      - "9411:9411" 
    depends_on:
      - otel-collector

  # zipkin:
  #   container_name: zipkin
  #   image: openzipkin/zipkin
  #   restart: always
  #   ports:
  #     - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
        - ./docker/otel-collector/otel-collector-config.yml:/etc/otel-collector-config.yml
      # - zipkin
