apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    orgId: 1
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    editable: false
    jsonData:
      httpMethod: GET
      timeInterval: "5s"
  - name: Loki
    type: loki
    uid: loki
    orgId: 1
    access: proxy
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    editable: false
