apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    orgId: 1
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    editable: false
    jsonData:
      httpMethod: GET
      timeInterval: "5s"